# Name of your site (displayed in the header)
title: Skatathon 2023

# Short bio or description (displayed in the header)
description: SMU Skatathon 2023

# the base hostname and protocol for your site, e.g. http://example.com
url: https://smuskatathon.github.io

github: [metadata]

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: /

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME